name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install 

      - name: Build the project
        run: npm run build 

      - name: Run tests with coverage
        run: npm run test -- --coverage
        
      - name: List contents of coverage directory
        run: ls -R ./coverage      
      
      - name: Upload coverage to Codecov (demo)
        uses: codecov/codecov-action@v3
        with:
           files: |
             ./coverage/calculator/coverage-final.json
             ./coverage/coverage-test/coverage-final.json
             ./coverage/coverage-final.json
           flags: demo,${{ matrix.os }}
           name: codecov-demo
           verbose: true
           token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload coverage to Codecov (version)
        uses: codecov/codecov-action@v3
        with:
          files: |
            ./coverage/calculator/coverage-final.json
            ./coverage/coverage-test/coverage-final.json
            ./coverage/coverage-final.json
          flags: version,${{ matrix.os }}
          name: codecov-version
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
